### ISSUE TITLE
ENV values are sometimes not interpolated

### ISSUE THREAD

**Issue by wagenet** [sagiegurari/cargo-make#419] opened 2020-05-01 19:01 UTC
```toml
[env]
FOO = "bar"
BAZ = { value = "${FOO}/lib", condition = { env_set = ["FOO"] } }
```

BAZ becomes `${FOO}/lib` instead of `bar/lib`.

**Comment by wagenet** [comment] 2020-05-01 19:12
Actually, it may be something else going on. I have the following lines in my `[env]`:
```
OPENSSL_LIB_DIR = "${DEP_DIR}/lib"
OPENSSL_INCLUDE_DIR = "${DEP_DIR}/include"
```

But during my build, I get:

```
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = /src/deps/i386-linux/lib
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = ${DEP_DIR}/include
```

I can't figure out why one seems to be interpolated and the other is not.

**Comment by wagenet** [comment] 2020-05-01 19:12
AFAICT, whichever one I specify last doesn't work as expected.

**Comment by sagiegurari** [comment] 2020-05-01 19:23
I created the below toml file which worked just fine.
so i would need a more accurate test case if you got one

```toml
[env]
FOO = "bar"
BAZ = { value = "${FOO}/lib", condition = { env_set = ["FOO"] } }
DEP_DIR="test"
OPENSSL_LIB_DIR = "${DEP_DIR}/lib"
OPENSSL_INCLUDE_DIR = "${DEP_DIR}/include"

[tasks.t]
script = [
'''
echo baz: ${BAZ}
echo LIB: ${OPENSSL_LIB_DIR}
echo INC: ${OPENSSL_INCLUDE_DIR}
'''
]
```

**Comment by wagenet** [comment] 2020-05-01 19:35
@sagiegurari thanks for taking a look. It's pretty baffling. I'll see what I can do to get a better reproduction.

**Comment by sagiegurari** [comment] 2020-05-06 17:00
@wagenet is this problem solved or do you still face an issue?

**Comment by wagenet** [comment] 2020-05-06 23:53
I haven't figured it out, but I guess you can close. I'll reopen if I have something more concrete to go on.

**Comment by sagiegurari** [comment] 2020-05-07 07:08
@wagenet is it possible that you had an issue when using env variables that are also defined in the stable.toml inside cargo-make? in which case load order might not be that straightforward?
or are these env vars with names that do not conflict?

**Comment by wagenet** [comment] 2020-05-07 17:57
I don't think the name should have conflicted.

**Comment by sagiegurari** [comment] 2020-05-07 18:16
ok, i had a hunch since if you override an env var that is defined in the internal makefile (stable.toml) than the real order is different than what you see as the original position from the stable.toml takes effect.
but if its something without CARGO_MAKE_ prefix... its probably not conflicting.
anyhow, i'll leave this issue open for now and lets see if you reproduce this.
if not, i'll close in few weeks.

**Comment by wagenet** [comment] 2020-05-07 19:17
@sagiegurari sounds good. I'll definitely keep that in mind when I investigate. It's possible I am remember incorrectly.

**Comment by sagiegurari** [comment] 2020-05-25 05:24
@wagenet i'm closing this one.
feel free to reopen or open a new issue if needed.

**Closed by sagiegurari** 2020-05-25 05:24 UTC
Labels: investigation
