### ISSUE TITLE
Please mention dependencies not handled by cargo for building cargo make.

### ISSUE THREAD

**Issue by YruamaLairba** [sagiegurari/cargo-make#403] opened 2020-04-01 22:13 UTC
Hello,

The first time i tried to build/install this app, the building process failed during the build of "open-ssl-sys". I get this error because the "libssl-dev" package was missing to my system. While this kind of issue is often easy to solve, this kind of prerequisite should be mentioned in the build/install process. In general, this avoid the annoying task of trying and failing the build for each missing dependencies.

**Comment by sagiegurari** [comment] 2020-04-02 14:44
Thanks a lot for the feedback.

That ssl dependency is not used directly by cargo-make but by other rust dependencies.
so this whole thing is kinda dynamic, as it may change in the future without even changing cargo-make version. so i'm not sure this should be documented.
also, in case of installation issues, there are also prebuilt versions available in the release page and that is documented at the top of the readme.

**Comment by gilescope** [comment] 2020-04-02 15:57
It's not immediately obvious why a make tool needs internet access. It would be cool if we could slim down these dependencies so that we had a build tool that was extremely easy (and fast) to build :-)

**Comment by sagiegurari** [comment] 2020-04-02 16:59
well... actually many build tools do need internet access.
cargo, maven, gradle, npm, so on and so forth are build tools that know how to download dependencies.
if you have it locally, ok. but if not, they fetch from remote server.

cargo make does the same, but more than that, if you call cargo plugins for example, it will download and install them for you (if needed) although they are not a dependency of your package, but you need it for your build flow.

for the ssl one, i suspect that its due to duckscript which is also mine.
its as scripting language that enables you to do lots of stuff and its embedded inside cargo-make.
it in turn, has a dependency on some rust http client (i picked the most minimal one) to enable you to write cargo-make scripts that do http calls (get/post). for example if you want to fetch via http some remote script/config/whatever. 

as for a build tool that is fast + easy to build, like i wrote, i have prebuild versions of it. nothing faster then downloading and unzipping :D

i'm a bit struggling to understand what is actionable here.
if it is to document, feel free to think of good phrasing that would be helpful and submit a PR.
i'll be happy to review it and see if it really solves an issue.
if it does, i'll merge it in.

**Comment by gilescope** [comment] 2020-04-02 18:58
I’m thinking that you might be able to get away with outsourcing all the networking - for the plugins you can call cargo install cargo-pluginname. Cargo itself is a great example of something that is non-trivial to build, but it’s already built so we can piggyback off it. Is duckscript an optional feature?

As a user it’s really helpful if there’s a build that can work with ideally almost all rust dependencies where possible- it means there’s a lot less setup. For build tools they get used in a lot of locations - lots of OSes, lots of CI places as well as developers machines. The single thing that can help ease of use for a build tool is it being easy to build.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sagiegurari** [comment] 2020-04-02 19:21
its not optional feature.
usually dependencies can be setup with features easily in cargo.toml, but installing binaries is not as they are system wide.
also, it is used in core tasks.
i very much think the issue is legit if it was actually a real issue to install, but with prebuit binaries available, its not.
and its much much faster than other binaries such as rustfmt or clippy.
removing dependencies from cargo make would mean removing capabilities and also making my life much harder to see if i can or can't do something.
sorry, but that is not an option.

**Comment by sagiegurari** [comment] 2020-04-02 19:48
I'm closing this one for now.
if you want to submit a documentation PR, I will review it.
i will however not remove features and fragment the code.

**Closed by sagiegurari** 2020-04-02 19:48 UTC
Labels: documentation, rejected
