### ISSUE TITLE
Allow multiple profiles from CLI

### ISSUE THREAD

**Issue by bluejekyll** [sagiegurari/cargo-make#343] opened 2019-12-23 22:45 UTC
**Features Description**

There is a feature for "additional_profiles" but I think it's a little limited at the moment, or maybe I don't really "get" what they are for. Today, I'm using the `env` section in tasks for specifying a feature set to test. For example, I have `dns-over-openssl` or `dns-over-rustls` features that need to be tested separately.

What I've done today is have an optional FEATURES environment variable that is set on a per task basis, for example:

```toml
[tasks.dns-over-openssl]
description = "Run all with --features=dns-over-openssl"
workspace = false
env = { FEATURES = "--features=dns-over-openssl", CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "crates/proto;crates/native-tls;crates/rustls;crates/https;tests/compatibility-tests;util" }
run_task = { name = "all", fork = true }
```

The issue is that this requires a task per feature. This is fine, except that it means that for each task type, say `all` (compile && test) we'd need a counter-part for the code coverage task, which would be a lot of duplicated config.

If the only env var was the FEATURES variable, this could be handled with just the cli parameter for setting environment variables, but then we couldn't also restrict the set of crates to test with CARGO_MAKE_WORKSPACE_SKIP_MEMBERS (since not all of them support the same features).

It seems like this would be a great use for profiles, but it's not clear how to do that at the moment where say you could combine the FEATURE profile with a CI, DEV, or RELEASE profile. Maybe I'm misunderstanding the docs, or possibly I'm trying to solve this problem in the wrong way.

**Describe the solution you'd like**

Allow multiple profiles to be combined via CLI arguments. e.g:

```console
> cargo make all -p ci -p dns-over-openssl
```

Load order would be left most first, to right most (maybe).

**Code Sample**

```toml
[env.ci]
CI = true

[env.dns-over-openssl]
FEATURES = "--features=dns-over-openssl"
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "crates/proto;crates/native-tls;crates/rustls;crates/https;tests/compatibility-tests;util"
```

**Comment by sagiegurari** [comment] 2019-12-24 07:46
Need to understand the actual issue first, because your original solution looks great to me.
so you have a task per feature that the user can request to build.
and the problem is the coverage being overwritten if the user is running ```cargo make feature1``` and then ```cargo make feature2```?
is coverage important if you are not running with all features enabled (i guess so)? because it means parts will not be tested.

**Comment by bluejekyll** [comment] 2019-12-24 09:04
> is coverage important if you are not running with all features enabled 

I mean, it's not hugely important, but it would be better.

I can mimic all the tasks that I have now with cov-${task} and do the same, but it just feels like a lot of duplication... that's all.

I'm also starting to adopt this for use in another project, and have a similar issue with sets of profiles that might be useful.

**Comment by sagiegurari** [comment] 2019-12-24 09:47
did you look at init tasks? that task is invoked always before the task the user selected in the cli.
by default its empty but you can override it, and then do a mapping in run_task of that init task which will invoke the relevant (new custom) task setup_env_dns_over_ssl/setup_env_feature2/...
and in those tasks you can have an env block that defines whatever you need.

would that prevent that duplication for coverage as well?
since its always invoked at the start of the flow no matter what and can be used to setup the env before hand (that's actually the reason for the init/end tasks, to setup and cleanup the env).

**Comment by sagiegurari** [comment] 2019-12-30 14:09
@bluejekyll is this resolved via init tasks or something more is needed?

**Comment by bluejekyll** [comment] 2019-12-30 15:29
Thanks for following up. I haven’t had a chance to try the solution you mentioned. It’s not clear to me how to use that to solve the issue in the way that I’ve considered it, but also, I’m not currently blocked so I wouldn’t call this a bug that has high urgency, if you want to close it.

**Comment by sagiegurari** [comment] 2020-03-25 23:09
i've been thinking about this one few times and i prefer not to have additional profiles also set via cli.
i'm not sure this is a blocker here, and i'm not sure how much additional profiles are used as a feature (i used it a lot).
i think profile is the main thing and additional just allow few tweaking so... i'm ok with leaving it as is.
closing for now, but feel free to reopen if something is missing and maybe we can take another look (especially with duckscript now being able to do a lot inside the cargo-make process).

**Closed by sagiegurari** 2020-03-25 23:09 UTC
Labels: low priority
