### ISSUE TITLE
Issue when using `clippy-preview` or `rustfmt-preview`

### ISSUE THREAD

**Issue by D4nte** [sagiegurari/cargo-make#119] opened 2018-10-29 03:09 UTC
#### Problem Description

`clippy-preview` and `rustfmt-preview` are part of the rust nursery. The [recommended way](https://github.com/rust-lang-nursery/rustfmt) to install them is: `rustup component add rustfmt-preview`

The following task fails as `clippy` cannot be found:

```toml
[tasks.clippy]
description = "Runs cargo clippy to check for warnings."
install_script = ["rustup component add clippy-preview"]
command = "cargo"
args = ["clippy", "--all", "--all-targets"]
```

```
03:04 $ cargo make clippy
[cargo-make] INFO - cargo-make 0.14.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: clippy
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: clippy
[cargo-make] INFO - Execute Command: "cargo" "clippy" "--all" "--all-targets"
error: toolchain 'nightly-2018-09-14-x86_64-apple-darwin' does not have the binary `cargo-clippy`
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```
This is because `install_script` is **not** ran.
I had to use the following code to fix the issue (not ideal)

```toml
[tasks.clippy]
description = "Runs cargo clippy to check for warnings."
install_script = ["rustup component add clippy-preview"]
script = ["cargo clippy --all --all-targets"]
```

Can you please either:
- ensure that `install_script` is actually always executed
- OR provide a way to install rust components: `install_component` feature?

## Assumption

My unconfirmed assumption is that `install_script` is not executed if the command is `cargo` and the sub-command `clippy` is found. Unfortunately, `clippy` is found for another toolchain and hence is not valid. I was not able to find this check for looking into the code but it seems it is an incorrect assumption that all cargo commands are installed via cargo.

**Comment by sagiegurari** [comment] 2018-10-29 04:06
your assumption is correct. installation is bypassed if specific cargo command already is available.
however the issue is real and I need to add rustup integration to resolve this problem which is something that i wanted to do.
so definitely this item is high priority.
thanks

**Comment by sagiegurari** [comment] 2018-11-03 17:57
tracked via #122 
coding is finished, but got to write more tests to verify it in multiple platforms.

**Comment by sagiegurari** [comment] 2018-11-05 19:19
just pushed clippy and rustfmt rustup configs to enable cargo-make to install it via rustup (and if fails via cargo install).
it's currently in the 0.15.0 development branch if you want to try it out (I'm planning to release more unrelated changes in 0.15.0 so it might take few more days to actually release it officially).

**Comment by thomaseizinger** [comment] 2018-11-05 21:37
Great! Thank you very much!
We will give it a try and report back if there are any issues :)

**Comment by D4nte** [comment] 2018-11-05 23:29
Thanks for the feature. Can you please clarify what rust version is needed. I tried with stable and my local nightly and I get the same compilation failure:

```
✘-101 ~/src/swap [cargo-make-rustup L|✚ 2⚑ 2]
23:27 $ cargo +nightly install --git https://github.com/sagiegurari/cargo-make.git --branch 0.15.0
    Updating git repository `https://github.com/sagiegurari/cargo-make.git`
  Installing cargo-make v0.14.0 (https://github.com/sagiegurari/cargo-make.git?branch=0.15.0#eb620639)
    Updating crates.io index
   Compiling version_check v0.1.5
   Compiling proc-macro2 v0.4.20
   Compiling cfg-if v0.1.6
   Compiling libc v0.2.43
   Compiling unicode-xid v0.1.0
   Compiling rand_core v0.3.0
   Compiling regex v1.0.5
   Compiling lazy_static v1.2.0
   Compiling serde v1.0.80
   Compiling ucd-util v0.1.2
   Compiling utf8-ranges v1.0.2
   Compiling unicode-width v0.1.5
   Compiling bitflags v1.0.4
   Compiling ansi_term v0.11.0
   Compiling semver-parser v0.7.0
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling rust_info v0.2.0
error[E0658]: `crate` in paths is experimental (see issue #45477)
  --> /Users/froyer/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_info-0.2.0/src/rustinfo.rs:10:5
   |
10 | use crate::types::{RustChannel, RustInfo};
   |     ^^^^^
   |
   = help: add #![feature(crate_in_paths)] to the crate attributes to enable

error[E0658]: `crate` in paths is experimental (see issue #45477)
   --> /Users/froyer/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_info-0.2.0/src/lib.rs:145:5
    |
145 | use crate::types::RustInfo;
    |     ^^^^^
    |
    = help: add #![feature(crate_in_paths)] to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rust_info`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-make v0.14.0 (https://github.com/sagiegurari/cargo-make.git?branch=0.15.0#eb620639)`, intermediate artifacts can be found at `/var/folders/bt/h5nbb7hs6pbcqd89tgn8ls5w0000gn/T/cargo-installVUYdSG`

Caused by:
  build failed
```

**Comment by D4nte** [comment] 2018-11-06 02:49
I saw that you use Rust 2018 and was able to install `cargo-make` from git using `+beta`.

Feedback: great to see it works with your default `fmt` and `clippy` tasks. Thank you!
I also have a `check-fmt` task (I am thinking about contributing it back to the default Makefile actually)

This configuration does not install `fmt` automatically:
```
[tasks.check-format]
description = "Runs cargo fmt to check appropriate code format."
workspace = false
command = "cargo"
args = ["fmt", "--", "--check"]
```

However, no issue with this configuration:
```
[tasks.check-format]
description = "Runs cargo fmt to check appropriate code format."
workspace = false
install_crate = { crate_name = "fmt", rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--", "--check"]
```

I am guessing it is the intended behavior but I wanted to report just in case.

**Comment by sagiegurari** [comment] 2018-11-06 03:56
thanks a lot for checking. ya fmt check should also have it. missed it.

**Comment by sagiegurari** [comment] 2018-11-13 07:06
fix for this has been published, except for the fmt check which I'll publish in coming days.
if you need anything more or if it doesn't work reopen the issue (or create a new one).

**Closed by sagiegurari** 2018-11-13 07:06 UTC
Labels: enhancement
