### ISSUE TITLE
env variable does not substitute to script

### ISSUE THREAD

**Issue by tower120** [sagiegurari/cargo-make#627] opened 2022-02-06 07:40 UTC
env variable does not substitute to script, if variable is first thing in the line.

Makefile.toml:
```rust
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
GODOT = "${CARGO_MAKE_WORKING_DIRECTORY}/../engine/godot_win64.exe"

...

[tasks.run-godot]
script_runner = "@shell"
script = '''
cd ../godot/
${GODOT} -d
'''
```

Output:
```
[cargo-make][1] INFO - Running Task: run-godot

C:\GodotProjects\my-awesome-game\rust>cd "C:\GodotProjects\my-awesome-game\rust"

C:\GodotProjects\my-awesome-game\rust>cd ../godot/

C:\GodotProjects\my-awesome-game\godot>${GODOT} -d
```

Switching to : 
```
script = '''
cd ../godot/
; ${GODOT} -d
'''
```
Solves the problem.

**Comment by sagiegurari** [comment] 2022-02-06 15:07
@tower120 thanks, i'm able to reproduce with your example.
The issue is in the shell2batch crate, so i'll fix it there and update here as well.

**Comment by sagiegurari** [comment] 2022-02-06 15:31
@tower120 this should be fixed now. just reinstall cargo-make and it should be ok.

**Closed** 2022-02-07 06:05 UTC
Labels: bug

**Comment by tower120** [comment] 2022-02-07 07:11
Many thanks! Fixed indeed.
