### ISSUE TITLE
Default to root workspace if member makefile was not found

### ISSUE THREAD

**Issue by adamski234** [sagiegurari/cargo-make#474] opened 2020-10-11 12:24 UTC
### Feature Description
When no `Makefile.toml` was found in the first member workspace, only apply the top level makefile. Or emit an error message pointing to the ability to have makefiles in members or the `--no-workspaces` flag.

### Describe The Solution You'd Like
When running `cargo make` in a workspace with multiple members, `cargo-make` looks inside each member's folder for `Makefile.toml` and errors if it was not found. This can be confusing for beginners, so, in my opinion, `cargo-make` should either give up on searching for makefiles in members, or let the user know about member makefiles, for example with a link to [the docs](https://sagiegurari.github.io/cargo-make/#usage-workspace-support).

**Comment by sagiegurari** [comment] 2020-10-11 12:28
not sure if i totally understand this one.
so you have members without a makefile in a workspace and it causes the build to fail?
because i also have a public github project with rust workspace, and one of the members does not have a specific makefile:
https://github.com/sagiegurari/duckscript/tree/master/duckscript
and it works just fine.
so i'm trying to fully understand the issue and solution requested.

**Comment by adamski234** [comment] 2020-10-11 13:20
My example: https://github.com/adamski234/ars-parser/blob/7fa083dca61540df2a813299731a012488e94744/Makefile.toml. When running `cargo make echo1` in that project, `cargo-make` goes to `ars_generator`, fails to find the makefile, and simply returns with error. My idea is that it should either tell me `ars_generator does not have a makefile` and a link to the docs about workspaces, or just run the top level makefile with `--no-workspaces`. I hope that clears it up

**Comment by sagiegurari** [comment] 2020-10-11 13:24
ah, the the issue not a missing makefile.
the issue is that it triggers cargo make in that member, and does'nt find the echo1 task because its not defined.
if you want members to get workspace level tasks automatically (only if triggered from workspace directory), add the following to your workspace makefile:

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
```

from the docs: https://github.com/sagiegurari/cargo-make#automatically-extend-workspace-makefile

if you however go directly to that member and try to run cargo-make only for that member from the member dir with echo1 task it will fail.
I tried to make the docs pretty detailed on the workspace support but i'm sure it could use more work.

**Comment by adamski234** [comment] 2020-10-11 16:30
My original idea was to either make that a default, or at least let the users know that it's looking for a member's makefile. It was a bit of my fault, as I didn't read that part of the docs, but I was following the introduction and got stuck on that part

**Comment by sagiegurari** [comment] 2020-10-11 17:46
ya, i know its a bit confusing. there are a lot of features and many ways of doing same thing.
for workspaces, in order to make a clear separation between crates to enable each crate to define its own logic of how doing things, i did not set it on by default.
for example you have a workspace with 2 members, 1 server and 1 client.
the build task for each might be very different (server might be cargo build, while client might actually use something else, or custom toolchain or cargo web and so on....).
so each one can define its own makefile with its own member logic instead of pilling it all up in the workspace level.
this allows to create workspaces with tens of members and still have things ordered.
i'm sure not everyone will agree, so you can do whatever you want in your workspace (like setting members to look at root workspace with that env var), but it feels more right to me.

**Comment by sagiegurari** [comment] 2020-10-12 17:18
i'm closing this one as I think it should work for you.
however, if you run into issues or got some questions, feel free to reopen/open a new issue

**Closed by sagiegurari** 2020-10-12 17:18 UTC
Labels: investigation
