### ISSUE TITLE
env override and makefile extending

### ISSUE THREAD

**Issue by x37v** [sagiegurari/cargo-make#523] opened 2021-03-06 01:15 UTC
I'm using `cargo make 0.32.13`

I have 2 Makefile.toml files

The first one defines
```
[env]
PACKAGE_NAME = { value = "foo", condition = { env_not_set = ["PACKAGE_NAME"] } }
PACKAGE_INSTALL_DIR = "${PACKAGE_NAME}/externals/"

[tasks.echo]
script_runner = "@shell"
script = [
'''
echo PACKAGE_INSTALL_DIR: ${PACKAGE_INSTALL_DIR}
'''
]
```

And the 2nd one extends the first
```
extend = "../path/to/Makefile.toml"

[env]
PACKAGE_NAME = "bar"
```

when I run `cargo make echo`in the directory with the extended makefile, I see:
`PACKAGE_INSTALL_DIR: ${PACKAGE_NAME}/externals/`

if I remove the `[env]` section from extended makefile I see:
`PACKAGE_INSTALL_DIR: foo/externals/`

If i keep it removed and run `PACKAGE_NAME=bar cargo make echo` i see:
`PACKAGE_INSTALL_DIR: bar/externals/`

So, maybe this is just a bug or am I messing something up? Is there a better way to do this? Basically, I have a variety of options in the base makefile that I'd like to be able to customize, names, paths, etc.

**Comment by sagiegurari** [comment] 2021-03-06 07:28
feels like a bug. i will check it out.
thanks for notifying me :)

**Comment by sagiegurari** [comment] 2021-03-06 14:38
@x37v this is now fixed in the 0.32.14 dev branch
thanks a lot for reporting. please tell me if it solves your issues.

**Comment by x37v** [comment] 2021-03-06 18:29
> @x37v this is now fixed in the 0.32.14 dev branch
> thanks a lot for reporting. please tell me if it solves your issues.

@sagiegurari that did it! thanks so much!

**Closed** 2021-03-06 18:30 UTC
Labels: bug

**Comment by cdmistman** [comment] 2021-08-06 01:20
Not sure if this is a regression or what, but I'm experiencing a bug that seems similar when running `cargo-make 0.35.0`:
```toml
[env]
TARGET = "hello"
CHK = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
TARGET_FILE = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/${TARGET}.json"

[tasks.print-env]
script = [
  # prints "TARGET=hello"
  "echo TARGET=${TARGET}",
  # prints "TARGET_FILE=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hello.json"
  "echo TARGET_FILE=${TARGET_FILE}",
  # prints "CHK=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
  "echo CHK=${CHK}",
  # prints "CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY=/this/path/is/correct"
  "echo CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}",
]
```

**Comment by sagiegurari** [comment] 2021-08-06 14:25
@cdmistman try the following:

```toml

[tasks.print-env]
script = [
  # prints "TARGET=hello"
  "echo TARGET=${TARGET}",
  # prints "TARGET_FILE=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/hello.json"
  "echo TARGET_FILE=${TARGET_FILE}",
  # prints "CHK=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
  "echo CHK=${CHK}",
  # prints "CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY=/this/path/is/correct"
  "echo CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY=${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}",
]
[tasks.print-env.env]
TARGET = "hello"
CHK = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
TARGET_FILE = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/${TARGET}.json"
```

The issue is that you are setting up global env vars based on other env vars that are defined a bit later.
for example CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY cannot be set globally by cargo-make as it is per task. you can have multiple tasks from different files and when you are in a context of a specific task only than its set.
so for task specific env vars, you must use by setting yours also in the contxt of a task.

**Comment by cdmistman** [comment] 2021-08-06 14:36
Gotcha, can the docs be fixed in that case? Under <https://github.com/sagiegurari/cargo-make#usage-env-vars-loading-order>, it's suggested that env vars such as `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` are loaded before the `[env]` table (2nd bullet point is `internal environment variables (see Global section)`, 5th bullet point is the global `[env]` table)

**Comment by cdmistman** [comment] 2021-08-06 14:42
Although I would have a preference for some of these variables to be set before visiting the `[env]` table to reduce the number of times I have to repeat defining that variable. In the above use-case I listed, I need to use `TARGET_FILE` for multiple rules, and using a variable like `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` in the `[env]` table for the directory of the containing makefile would make pointing to the example `.json` file consistent across the workspace

**Comment by sagiegurari** [comment] 2021-08-06 14:45
you could create a task to define the env vars you need and have it as a dependency.
the vars set would last the entire process so you can access them in other tasks.

as for the docs, I'll clarify it more. thanks for the feedback.

**Comment by cdmistman** [comment] 2021-08-06 14:46
ah yes that makes sense! thank you! :)
