### ISSUE TITLE
Environment variable issue on windows

### ISSUE THREAD

**Issue by Cokemonkey11** [sagiegurari/cargo-make#62] opened 2018-01-21 23:12 UTC
The following won't work as expected on bash nor msys2:

```
[config]
skip_core_tasks = true

[tasks.default]
script = [
    "echo \"var: ${CARGO_MAKE_CRATE_VERSION}\""
]
```

Emits:

```
$ cargo make
[cargo-make] INFO - cargo-make 0.9.4
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Running Task: default

C:\workspace2\gen>cd C:\workspace2\gen

C:\workspace2\gen>echo "var: ${CARGO_MAKE_CRATE_VERSION}"
"var: ${CARGO_MAKE_CRATE_VERSION}"
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Build Done  in 0 seconds.
```

**Comment by sagiegurari** [comment] 2018-01-22 04:15
Windows use the %var% syntax.
In order to use bash syntax on windows you must tell which runner to use.
You should do that on [platform override task](https://github.com/sagiegurari/cargo-make#usage-platform-override) in order not to impact linux/mac execution.
For example:

```toml
[tasks.default.windows]
# if we want to keep rest of task definition just define the runner for windows
# and rest will be taken from original task
script_runner = "bash" 
```

Another option is to use the cross platform shell runner that can convert only very basic scripts from shell to batch if task is executed on windows. See [docs](https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-exampleshell2batch)

```toml
[tasks.shell]
script_runner = "@shell"
script = [
'''
rm ./myfile.txt
'''
]
```

**Comment by sagiegurari** [comment] 2018-01-24 18:14
@Cokemonkey11 does it resolve your issue or do you need any changes?

**Comment by Cokemonkey11** [comment] 2018-01-28 20:11
Hi,

Sorry for the huge delay.

My concern then is that when executing in a bash enviroment on a windows host (for example with MSYS2), the script runner choses windows style script.

I think this is also a design smell. I think script_runner should always default to unix-style shell.

How is this being detected, by the way?

**Comment by sagiegurari** [comment] 2018-01-28 21:58
I have to disagree, I think it should default based on the OS default shell and let the user change that manually, which you can.
That is why I have
* OS task overrides
* Ability to define what runner you want
* ```@shell``` runner
So you have complete freedom, but default should be based on OS.

Its been done using normal rust cfg! macro and implemented in the run_script crate (https://github.com/sagiegurari/run_script)
So if no runner is provided it defaults to something like:

```rust
if cfg!(windows) {
  "cmd.exe"
} else {
  "sh"
}
```

**Comment by Cokemonkey11** [comment] 2018-02-01 23:52
I think your response is of the form "run_script doesn't do the right thing here"

Fundamentally, I'm running in a shell environment, and my OS has quite little to do with that.

That doesn't mean the onus is on you to change it though

**Comment by sagiegurari** [comment] 2018-02-09 10:14
Don't think run_script doesn't do the right thing. I wrote it, so it actually does what I wanted it to :)
Right now, I think everything works by design which to me makes sense to use the OS native capabilities per OS and cargo-make gives you the ability to change that if you wish.
I do not see some actionable item here for cargo-make itself unless you feel something can be done better and give me some suggestions.

**Comment by sagiegurari** [comment] 2018-02-23 13:55
closing due to no feedback

**Closed by sagiegurari** 2018-02-23 13:55 UTC
Labels: question

**Comment by Cokemonkey11** [comment] 2018-03-04 18:24
Sorry, didn't mean to blank you. No feedback at this time. My view is that, given that `script` can do pretty naughty things if using the wrong runner, the rust way would be to panic/fail/stop if there's a mismatch between the script runner and the actual environment/platform.
